/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package draw.cli;

import draw.cli.Controller;
import draw.model.Canvas;
import draw.parser.Parser;
import draw.parser.ParsedCommand;

public class App {

    public static void main(String[] args) {

        Controller controller = new Controller(); 
        Parser parser = new Parser();

        while(true) {
            run(controller, parser);
        }

    }

    public static void run(Controller controller, Parser parser) {
        try {
            ParsedCommand parsedCommand = parser.parse();
            controller.execute(parsedCommand);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
