/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package draw.cli;

import draw.model.Canvas;
import draw.command.*;
import draw.parser.ParsedCommand;
import static draw.parser.ParsedCommand.CommandType;

import lombok.NoArgsConstructor;

@NoArgsConstructor
public class Controller {

    Canvas canvas = new Canvas();

    public void execute(ParsedCommand pc) {
        try {
            Command command = findCommand(pc);
            command.execute();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private Command findCommand(ParsedCommand pc) throws Exception {
        switch(pc.getType()) {
            case LINE:
                return new LineCommand(canvas, pc);
            case RECT:
                return new RectangleCommand(canvas, pc);
            case QUIT:
                return new QuitCommand();
            case CANVAS:
                return new CanvasCommand(canvas, pc);
            case FILL:
                return new FillCommand(canvas, pc);
            default:
                throw new Exception("Unrecognized command.");
        }
    }
}
