/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package draw.cli;

import draw.model.Point;

public class Printer {

    public static void print(Point[][] canvas) {

        int height = canvas.length;
        int width = canvas[0].length;

        for (int i=0; i<height; i++) {
            for (int j=0; j<width; j++) {
                char color = canvas[i][j].getColor();

                System.out.print(color);
            }
            System.out.println();
        }
    }
}
